tournament_rankings_array = {
    'MAX': [1500],
    'GRACEY': [1500],
    'BOGDAN': [1500],
    'CHRISTIAN': [1500],
    'HAYWAD': [1500],
    'JESSIE': [1500],
    'GRACEZ': [1500],
    'JUSTIN': [1500],
    'PAUL': [1500],
    'SAMSON': [1500],
    'PHILLIP': [1500],
    'PREM': [1500],
    'SHUOTONG': [1500],
    'ANNA': [1500],
    'CARMEN': [1500],
}

points_gained_after_each_round = {
    'BOGDAN': [1500],
    'PREM': [1500],
    'ANNA': [1500],
    'HAYWAD': [1500],
    'SAMSON': [1500],
    'GRACEZ': [1500],
    'MAX': [1500],
    'CARMEN': [1500],
    'CHRISTIAN': [1500],
    'GRACEY': [1500],
    'JESSIE': [1500],
    'JUSTIN': [1500],
    'PAUL': [1500],
    'PHILLIP': [1500],
    'SHUOTONG': [1500],
}

tournament_match_array = [
    ["MAX", "GRACEY", 15, 13, 1],
    ["BOGDAN", "CHRISTIAN", 15, 1, 1],
    ["JESSIE", "HAYWAD", 13, 15, 1],
    ["GRACEZ", "JUSTIN", 15, 10, 1],
    ["PAUL", "SAMSON", 5, 15, 1],
    ["PHILLIP", "PREM", 8, 15, 1],
    ["SHUOTONG", "ANNA", 5, 15, 1],
    ["MAX", "BOGDAN", 6, 15, 2],
    ["HAYWAD", "GRACEZ", 15, 9, 2],
    ["SAMSON", "PREM", 9, 15, 2],
    ["ANNA", "CARMEN", 15, 3, 2],
    ["BOGDAN", "HAYWAD", 15, 4, 3],
    ["BOGDAN", "HAYWAD", 15, 1, 3],
    ["PREM", "ANNA", 15, 8, 4],
    ["PREM", "ANNA", 15, 6, 4],
    ["BOGDAN", "PREM", 15, 10, 5],
    ["BOGDAN", "PREM", 15, 7, 5],
]

regular_match_rankings_array = {
    "BOGDAN": [1602],
    "PREM": [1564],
    "ANNA": [1551],
    "HAYWAD": [1536],
    "SAMSON": [1531],
    "GRACEZ": [1521],
    "GRACEY": [1500],
    "MAX": [1520],
    "CARMEN": [1500],
    "CHRISTIAN": [1500],
    "JESSIE": [1500],
    "JUSTIN": [1500],
    "PAUL": [1500],
    "PHILLIP": [1500],
    "SHUOTONG": [1500],
    "TUSHAR": [1500],
    "GAB": [1500],
    "JACK": [1500],
    "NESMA": [1500],
    "JEREMY": [1500],
    "ANTHONY": [1500],
    "CERI": [1500],
    "WILSON": [1500]
}

regular_match_array = [
    ["PREM", "HAYWAD", 13, 15, None],
    ["PREM", "SAMSON", 6, 11, None],
    ["PREM", "SAMSON", 11, 7, None],
    ["PREM", "SAMSON", 11, 5, None],
    ["SAMSON", "PREM", 6, 11, None],
    ["PAUL", "PHILLIP", 12, 15, None],
    ["PREM", "PHILLIP", 12, 3, None],
    ["JUSTIN", "ANNA", 7, 11, None],
    ["ANNA", "GRACEY", 15, 7, None],
    ["SAMSON", "PREM", 11, 13, None],
    ["PHILLIP", "SAMSON", 12, 15, None],
    ["PREM", "SAMSON", 11, 5, None],
    ["PREM", "SAMSON", 12, 10, None],
    ["HAYWAD", "SAMSON", 11, 15, None],
    ["PAUL", "SAMSON", 11, 15, None],
    ["ANNA", "SAMSON", 12, 15, None],
    ["PHILLIP", "PAUL", 8, 15, None],
    ["PHILLIP", "PAUL", 10, 15, None],
    ["PAUL", "SAMSON", 12, 15, None],
    ["BOGDAN", "PREM", 14, 12, None],
    ["JUSTIN", "GRACEZ", 15, 10, None],
    ["JUSTIN", "ANNA", 8, 15, None],
    ["PHILLIP", "PAUL", 14, 16, None],
    ["PREM", "HAYWAD", 15, 8, None],
    ["PAUL", "PHILLIP", 11, 15, None],
    ["ANNA", "PHILLIP", 10, 15, None],
    ["GRACEZ", "SAMSON", 8, 11, None],
    ["TUSHAR", "ANNA", 15, 12, None],
    ["PAUL", "PHILLIP", 15, 7, None],
    ["PHILLIP", "ANNA", 15, 8, None],
    ["PREM", "ANNA", 16, 14, None],
    ["PHILLIP", "GRACEY", 19, 17, None],
    ["PREM", "PAUL", 15, 13, None],
    ["PHILLIP", "ANNA", 12, 15, None],
    ["PAUL", "PHILLIP", 16, 14, None],
    ["PAUL", "ANNA", 13, 15, None],
    ["PREM", "ANNA", 15, 13, None],
    ["PAUL", "PHILLIP", 15, 10, None],
    ["JUSTIN", "GRACEY", 18, 16, None],
    # Thursday September 28
    ["PREM", "HAYWAD", 15, 12, None],
    ["PAUL", "PHILLIP", 15, 12, None],
    ["ANNA", "TUSHAR", 11, 15, None],
    ["PREM", "TUSHAR", 11, 15, None],
    ["TUSHAR", "PAUL", 10, 15, None],
    ["PHILLIP", "ANNA", 12, 15, None],
    ["PHILLIP", "JUSTIN", 16, 14, None],
    ["GRACEZ", "CARMEN", 9, 11, None],
    ["JUSTIN", "CARMEN", 11, 9, None],
    ["GRACEZ", "GRACEY", 5, 11, None],
    ["PREM", "HAYWAD", 15, 11, None],
    ["HAYWAD", "PREM", 12, 15, None],
    ["ANNA", "GRACEY", 15, 5, None],
    # Friday September 29
    ["ANNA", "BOGDAN", 14, 16, None],
    ["PHILLIP", "JUSTIN", 11, 7, None],
    ["PHILLIP", "ANNA", 9, 15, None],
    ["PHILLIP", "PREM", 1, 15, None],
    ["PHILLIP", "PREM", 2, 15, None],
    ["GRACEY", "ANNA", 15, 11, None],
    ["JUSTIN", "CARMEN", 7, 11, None],
    ["ANNA", "PAUL", 15, 11, None],
    ["JUSTIN", "TUSHAR", 7, 15, None],
    ["JUSTIN", "ANNA", 8, 15, None],
    ["PAUL", "TUSHAR", 9, 15, None],
    # Monday October 2
    # Tuesday October 3
    ["PREM", "ANNA", 15, 7, None],
    ["PREM", "ANNA", 15, 10, None],
    ["NESMA", "GRACEY", 7, 11, None],
    ["PAUL", "PHILLIP", 15, 8, None],
    ["PHILLIP", "PAUL", 15, 10, None],
    ["TUSHAR", "GRACEY", 15, 13, None],
    ["PHILLIP", "ANNA", 9, 15, None],
    ["JUSTIN", "CARMEN", 7, 11, None],
    ["PAUL", "TUSHAR", 15, 11, None],
    ["JUSTIN", "ANNA", 8, 15, None],
    ["ANNA", "JUSTIN", 15, 12, None],
    ["TUSHAR", "PAUL", 15, 10, None],
    ["PHILLIP", "JACK", 15, 7, None],
    ["PHILLIP", "GAB", 15, 6, None],
    ["GRACEY", "CARMEN", 15, 9, None],
    ["GAB", "JUSTIN", 8, 15, None],
    ["TUSHAR", "ANNA", 15, 9, None],
    ["PAUL", "ANNA", 13, 15, None],
    ["PAUL", "GRACEY", 15, 6, None],
    ["JUSTIN", "GRACEY", 15, 11, None],
    ["GAB", "GRACEY", 15, 11, None],
    ["PREM", "GRACEY", 15, 11, None],
    #   Wednesday October 4
    ["PAUL", "TUSHAR", 9, 15, None],
    ["GRACEY", "ANNA", 9, 15, None],
    ["TUSHAR", "JUSTIN", 15, 7, None],
    ["PREM", "TUSHAR", 19, 17, None],
    ["PREM", "TUSHAR", 15, 11, None],
    ["PAUL", "ANNA", 15, 9, None],
    ["JUSTIN", "GRACEZ", 7, 11, None],
    ["JUSTIN", "CARMEN", 11, 7, None],
    ["GAB", "CHRISTIAN", 16, 14, None],
    ["PREM", "JUSTIN", 15, 13, None],
    ["ANNA", "PAUL", 12, 15, None],
    ["PREM", "PAUL", 15, 4, None],
    # Thursday October 5
    ["PREM", "JUSTIN", 15, 0, None],
    ["JUSTIN", "PREM", 6, 15, None],
    ["JUSTIN", "ANNA", 7, 15, None],
    ["GRACEY", "ANNA", 5, 15, None],
    ["GRACEY", "PHILLIP", 10, 15, None],
    ["JUSTIN", "PHILLIP", 10, 15, None],
    ["GAB", "JACK", 11, 15, None],
    ["GRACEY", "JACK", 15, 3, None],
    ["TUSHAR", "PHILLIP", 15, 7, None],
    ["ANNA", "PREM", 9, 15, None],
    ["BOGDAN", "TUSHAR", 17, 15, None],
    ["PAUL", "ANNA", 11, 15, None],
    ["GAB", "PHILLIP", 8, 15, None],
    ["PHILLIP", "PREM", 8, 15, None],
    ["GAB", "PREM", 7, 15, None],
    ["PREM", "PAUL", 15, 8, None],
    ["ANNA", "PAUL", 15, 10, None],
    # Friday October 6
    ["PHILLIP", "JUSTIN", 15, 7, None],
    ["JUSTIN", "GAB", 11, 3, None],
    ["GRACEY", "PREM", 6, 15, None],
    ["PREM", "TUSHAR", 15, 13, None],
    ["TUSHAR", "PREM", 15, 12, None],
    ["PHILLIP", "PREM", 7, 15, None],
    ["PREM", "PHILLIP", 16, 14, None],
    # Tuesday October 10
    ["PHILLIP", "PAUL", 15, 12, None],
    ["GAB", "JACK", 15, 12, None],
    ["GAB", "PAUL", 10, 15, None],
    ["NESMA", "PHILLIP", 6, 15, None],
    ["ANNA", "PHILLIP", 15, 7, None],
    ["PAUL", "PREM", 11, 15, None],
    # Wednesday October 11
    ["ANNA", "JUSTIN", 17, 15, None],
    ["ANNA", "PREM", 15, 10, None],
    ["PHILLIP", "PAUL", 15, 13, None],
    ["GRACEZ", "JACK", 14, 16, None],
    ["PAUL", "GAB", 15, 8, None],
    ["PAUL", "NESMA", 11, 6, None],
    ["PHILLIP", "PREM", 10, 15, None],
    ["ANNA", "GRACEY", 15, 7, None],
    ["PHILLIP", "ANNA", 14, 16, None],

    # Thursday October 12
    ["PHILLIP", "JUSTIN", 19, 17, None],
    ["PREM", "ANNA", 10, 15, None],
    ["ANNA", "PREM", 15, 12, None],
    ["ANNA", "TUSHAR", 13, 15, None],
    ["ANTHONY", "GRACEY", 7, 15, None],
    ["TUSHAR", "PAUL", 15, 11, None],
    ["PAUL", "PHILLIP", 15, 17, None],
    ["GAB", "PHILLIP", 8, 15, None],
    ["GAB", "ANNA", 4, 15, None],
    ["JUSTIN", "GAB", 15, 8, None],
    ["TUSHAR", "PREM", 15, 13, None],
    ["GRACEY", "JUSTIN", 15, 10, None],
    ["PHILLIP", "PAUL", 12, 15, None],
    ["ANTHONY", "JUSTIN", 10, 15, None],
    # Friday October 13
    ["PAUL", "JACK", 15, 3, None],
    ["JUSTIN", "ANTHONY", 15, 10, None],
    ["JUSTIN", "PREM", 8, 15, None],
    ["JACK", "GAB", 15, 8, None],
    ["PREM", "PAUL", 15, 5, None],
    ["PREM", "ANNA", 15, 7, None],
    ["PAUL", "ANTHONY", 15, 5, None],
    ["PAUL", "ANNA", 14, 16, None],
    ["PREM", "ANNA", 15, 7, None],
    ["PREM", "GAB", 15, 4, None],
    ["NESMA", "GRACEZ", 12, 15, None],
    ["PAUL", "PHILLIP", 15, 11, None],
    ["PHILLIP", "PREM", 11, 15, None],
    ["PREM", "GRACEZ", 15, 9, None],
    ["PREM", "ANTHONY", 15, 4, None],
    ["GAB", "PHILLIP", 2, 15, None],
    ["ANTHONY", "GAB", 11, 15, None],
    ["JUSTIN", "PAUL", 7, 15, None],
    # Monday October 16
    ["PREM", "ANNA", 15, 9, None],
    ["ANNA", "PREM", 10, 15, None],
    ["PAUL", "PHILLIP", 15, 10, None],
    ["PREM", "PHILLIP", 15, 7, None],
    ["PHILLIP", "PREM", 15, 10, None],
    ["TUSHAR", "ANTHONY", 15, 7, None],
    ["TUSHAR", "ANNA", 15, 9, None],
    ["PHILLIP", "TUSHAR", 5, 15, None],
    ["PHILLIP", "ANNA", 15, 11, None],
    ["ANNA", "PHILLIP", 15, 10, None],
    ["PHILLIP", "ANNA", 15, 10, None],
    ["TUSHAR", "PREM", 10, 15, None],
    ["PREM", "TUSHAR", 15, 8, None],
    ["GAB", "JACK", 14, 16, None],
    ["GRACEZ", "GAB", 17, 15, None],
    # Tuesday October 17
    ["PHILLIP", "JUSTIN", 12, 15, None],
    ["PAUL", "PHILLIP", 16, 18, None],
    ["TUSHAR", "GRACEY", 15, 11, None],
    ["TUSHAR", "ANNA", 15, 10, None],
    ["PHILLIP", "ANNA", 15, 11, None],
    ["ANNA", "PHILLIP", 4, 15, None],
    ["JACK", "GAB", 15, 6, None],
    ["PHILLIP", "GRACEY", 15, 10, None],
    ["PAUL", "ANNA", 13, 15, None],
    ["JUSTIN", "GAB", 15, 5, None],
    ["JUSTIN", "GRACEY", 15, 17, None],
    ["TUSHAR", "ANTHONY", 15, 8, None],
    ["PAUL", "GAB", 15, 10, None],
    ["ANTHONY", "GAB", 15, 10, None],
    ["PAUL", "PHILLIP", 17, 15, None],
    ["GRACEZ", "JACK", 13, 15, None],
    ["JUSTIN", "ANTHONY", 15, 13, None],
    ["TUSHAR", "GAB", 15, 9, None],
    ["ANNA", "PAUL", 13, 15, None],
    ["JUSTIN", "ANTHONY", 13, 15, None],
    # Wednesday October 18
    ["JUSTIN", "ANTHONY", 5, 15, None],
    ["GRACEZ", "GAB", 7, 15, None],
    ["ANNA", "GRACEY", 15, 13, None],
    ["PHILLIP", "PAUL", 11, 15, None],
    ["PREM", "GRACEZ", 15, 6, None],
    ["GAB", "JACK", 15, 13, None],
    ["GAB", "NESMA", 15, 17, None],
    ["PREM", "ANNA", 15, 12, None],
    ["PREM", "PHILLIP", 15, 10, None],
    ["TUSHAR", "PREM", 15, 2, None],
    ["ANTHONY", "GAB", 10, 15, None],
    ["NESMA", "GRACEZ", 6, 15, None],
    ["ANNA", "PAUL", 15, 7, None],
    ["JUSTIN", "PHILLIP", 12, 15, None],
    ["PREM", "ANNA", 9, 15, None],
    ["PREM", "GRACEY", 15, 5, None],
    ["ANTHONY", "JUSTIN", 11, 15, None],
    ["GAB", "GRACEY", 15, 12, None],
    ["GAB", "GRACEY", 15, 12, None],
    ["PHILLIP", "PAUL", 22, 20, None],
    ["PAUL", "PHILLIP", 16, 14, None],
    # Thursday October 19
    ["BOGDAN", "TUSHAR", 11, 6, None],
    ["JUSTIN", "ANTHONY", 10, 15, None],
    ["ANNA", "GRACEY", 15, 3, None],
    ["PHILLIP", "PAUL", 11, 15, None],
    ["ANNA", "TUSHAR", 11, 15, None],
    ["GAB", "TUSHAR", 11, 15, None],
    ["PREM", "TUSHAR", 17, 15, None],
    ["GAB", "NESMA", 11, 15, None],
    ["ANNA", "GAB", 15, 7, None],
    ["GRACEZ", "JACK", 12, 15, None],
    ["PAUL", "PREM", 13, 15, None],
    ["GRACEY", "GRACEZ", 15, 11, None],
    ["PAUL", "PHILLIP", 15, 4, None],
    ["PAUL", "PREM", 11, 15, None],
    # Friday October 20
    ["PAUL", "TUSHAR", 11, 15, None],
    ["JUSTIN", "ANTHONY", 16, 14, None],
    ["GAB", "ANTHONY", 15, 13, None],
    ["JUSTIN", "ANTHONY", 16, 14, None],
    ["PREM", "PAUL", 15, 11, None],
    ["GAB", "PHILLIP", 16, 14, None],
    ["GAB", "ANTHONY", 15, 7, None],
    ["JACK", "GAB", 13, 15, None],
    ["NESMA", "GAB", 13, 15, None],

    # TOURNAMENT GAME
    #   ["PAUL", "TUSHAR", 13, 15, None],

    # Monday October 23
    ["JUSTIN", "GRACEY", 15, 7, None],
    ["PHILLIP", "ANNA", 11, 15, None],
    ["PREM", "ANNA", 15, 3, None],
    ["PREM", "TUSHAR", 15, 5, None],
    ["TUSHAR", "GRACEZ", 15, 3, None],
    ["PAUL", "PHILLIP", 15, 12, None],
    ["GRACEZ", "JACK", 9, 15, None],
    ["GAB", "JACK", 8, 15, None],
    ["GRACEZ", "JUSTIN", 15, 12, None],
    ["GAB", "JUSTIN", 16, 14, None],
    ["PHILLIP", "PAUL", 7, 15, None],
    #   ["JUSTIN", "ANTHONY", , , None],
    ["PREM", "GAB", 15, 0, None],
    ["PREM", "PAUL", 15, 0, None],
    ["JACK", "PHILLIP", 7, 15, None],
    ["PREM", "GRACEY", 15, 1, None],
    ["ANNA", "TUSHAR", 11, 15, None],
    ["ANTHONY", "TUSHAR", 4, 15, None],
    ["PHILLIP", "TUSHAR", 10, 15, None],
    ["TUSHAR", "PHILLIP", 15, 8, None],

    # Tuesday October 24
    ["JACK", "PAUL", 8, 15, None],
    ["PAUL", "ANTHONY", 15, 8, None],
    ["TUSHAR", "GRACEY", 15, 4, None],
    ["PHILLIP", "TUSHAR", 13, 15, None],
    ["PAUL", "ANNA", 16, 14, None],
    ["PREM", "TUSHAR", 10, 15, None],
    ["GAB", "NESMA", 15, 13, None],
    ["GAB", "ANTHONY", 15, 9, None],
    ["PHILLIP", "ANNA", 18, 16, None],
    ["PREM", "ANTHONY", 15, 7, None],
    ["GRACEZ", "CARMEN", 8, 15, None],
    ["PAUL", "PHILLIP", 8, 15, None],
    ["ANTHONY", "JUSTIN", 15, 7, None],
    ["JACK", "GRACEY", 6, 15, None],
    ["TUSHAR", "GRACEZ", 15, 11, None],
    ["PHILLIP", "GRACEY", 12, 15, None],
    ["ANNA", "PAUL", 15, 10, None],
    ["ANTHONY", "ANNA", 0, 15, None],
    ["JUSTIN", "ANTHONY", 15, 13, None],

  # Wednesday October 25
  ["PHILLIP", "PAUL", 11, 15, None],
  ["GAB", "PAUL", 9, 15, None],
  ["JUSTIN", "ANTHONY", 15, 17, None],
  ["JUSTIN", "PREM", 5, 15, None],
  ["GRACEZ", "GAB", 15, 8, None],
  ["GRACEZ", "TUSHAR", 5, 15, None],
  ["ANNA", "PHILLIP", 15, 10, None],
  ["ANNA", "PHILLIP", 15, 9, None],
  ["PREM", "TUSHAR", 15, 10, None],
  ["GAB", "NESMA", 15, 8, None],
  ["JACK", "GAB", 15, 13, None],
  ["ANTHONY", "PAUL", 9, 15, None],
  ["JACK", "PHILLIP", 9, 15, None],
  ["PREM", "PHILLIP", 9, 15, None],
  ["ANTHONY", "GAB", 15, 8, None],
  ["PREM", "PAUL", 10, 15, None],
  ["PREM", "ANNA", 15, 9, None],
  ["GRACEY", "PHILLIP", 15, 11, None],
  # Thursday October 26
  ["GRACEZ", "JACK", 7, 15, None],
  ["PHILLIP", "PAUL", 11, 15, None],
  ["GAB", "TUSHAR", 1, 15, None],
  ["PAUL", "PHILLIP", 13, 15, None],
  ["PREM", "TUSHAR", 11, 15, None],
  ["TUSHAR", "GRACEZ", 15, 7, None],
  ["ANTHONY", "JUSTIN", 15, 12, None],
  ["ANTHONY", "PREM", 6, 15, None],
  ["PHILLIP", "ANNA", 19, 21, None],
  ["ANNA", "PHILLIP", 15, 12, None],
  ["ANTHONY", "GRACEZ", 15, 7, None],
  ["GAB", "CARMEN", 15, 13, None],
  ["ANTHONY", "PAUL", 7, 15, None],
  ["PREM", "PAUL", 15, 8, None],
  ["GRACEY", "GAB", 15, 8, None],
  ["ANNA", "GRACEY", 15, 10, None],
  ["ANNA", "ANTHONY", 15, 9, None],
  ["ANNA", "PREM", 12, 15, None],
  ["TUSHAR", "JUSTIN", 15, 6, None],
  ["JUSTIN", "GAB", 15, 6, None],
  ["ANTHONY", "TUSHAR", 5, 15, None],
#   ["NESMA", "CERI", 15, 5, None],
  ["GAB", "GRACEZ", 5, 15, None],
  # Friday October 27
  ["PAUL", "JACK", 15, 6, None],
  ["TUSHAR", "PHILLIP", 15, 11, None],
  ["ANTHONY", "PREM", 12, 15, None],
  ["GAB", "JACK", 15, 13, None],
  ["GAB", "GRACEZ", 12, 15, None],
  ["ANTHONY", "GAB", 15, 17, None],
  ["PREM", "TUSHAR", 7, 15, None],
  ["GRACEZ", "PHILLIP", 5, 15, None],
  ["JACK", "PHILLIP", 8, 15, None],
  ["JUSTIN", "GAB", 12, 15, None],
  ["ANNA", "PAUL", 17, 15, None],
  ["ANNA", "PHILLIP", 15, 5, None],
  ["GRACEY", "TUSHAR", 2, 15, None],
  ["PHILLIP", "GAB", 15, 13, None],
  ["GAB", "PHILLIP", 11, 15, None],
  ["PAUL", "JUSTIN", 15, 12, None],
  ["ANTHONY", "JUSTIN", 15, 9, None],
  ["ANTHONY", "GRACEY", 20, 18, None],
  # Monday October 30
  ["PAUL", "PHILLIP", 15, 13, None],
  ["JACK", "GAB", 8, 15, None],
  ["ANTHONY", "PREM", 12, 15, None],
  ["JUSTIN", "ANTHONY", 10, 15, None],
  ["PHILLIP", "ANNA", 12, 15, None],
  ["ANNA", "PHILLIP", 15, 5, None],
  # Tuesday October 31
  ["ANTHONY", "TUSHAR", 13, 15, None],
  ["GAB", "PREM", 6, 15, None],
  ["ANTHONY", "PREM", 5, 15, None],
  ["ANNA", "PHILLIP", 15, 13, None],
  ["PHILLIP", "ANNA", 10, 15, None],
  ["PHILLIP", "PAUL", 10, 15, None],
  ["TUSHAR", "PREM", 9, 15, None],
  ["PAUL", "PHILLIP", 15, 12, None],
  ["ANTHONY", "TUSHAR", 7, 15, None],
  ["GAB", "PAUL", 7, 15, None],
  ["GAB", "PHILLIP", 6, 15, None],
  ["GAB", "ANTHONY", 5, 15, None],
  ["PHILLIP", "ANNA", 9, 15, None],
  ["ANNA", "PHILLIP", 15, 13, None],
  ["JUSTIN", "ANTHONY", 17, 19, None],
  ["GAB", "GRACEZ", 19, 17, None],
  # Wednesday November 1
  ["ANTHONY", "JUSTIN", 15, 12, None],
  ["PHILLIP", "GAB", 15, 12, None],
  ["GAB", "ANTHONY", 15, 13, None],
  ["GAB", "GRACEZ", 1, 15, None],
  ["PHILLIP", "GRACEZ", 15, 9, None],
  ["GAB", "ANTHONY", 8, 15, None],
  ["PAUL", "ANTHONY", 15, 12, None],
  ["ANNA", "PHILLIP", 15, 4, None],
  ["PHILLIP", "ANNA", 16, 14, None],
  ["PREM", "ANNA", 15, 17, None],
  ["JUSTIN", "TUSHAR", 13, 15, None],
  ["PAUL", "TUSHAR", 14, 16, None],
  ["ANNA", "PAUL", 15, 10, None],
  ["PHILLIP", "TUSHAR", 10, 15, None],
  ["ANNA", "TUSHAR", 15, 7, None],
  ["JUSTIN", "GAB", 15, 7, None],
  # Thursday November 2
  ["JACK", "PAUL", 5, 15, None],
  ["GRACEZ", "GAB", 16, 14, None],
  ["PAUL", "PHILLIP", 15, 11, None],
  ["PHILLIP", "PAUL", 15, 13, None],
  ["PREM", "PHILLIP", 15, 9, None],
  ["JUSTIN", "ANTHONY", 15, 13, None],
  ["GAB", "JACK", 13, 15, None],
  ["GAB", "ANNA", 15, 8, None],
  ["PAUL", "PHILLIP", 12, 15, None],
  ["TUSHAR", "ANTHONY", 16, 14, None],
  ["TUSHAR", "GAB", 15, 10, None],
  ["PREM", "TUSHAR", 15, 11, None],
  ["TUSHAR", "PREM", 15, 13, None],
  ["PAUL", "GAB", 15, 4, None],
  ["PHILLIP", "ANNA", 9, 15, None],
  ["ANNA", "PHILLIP", 5, 15, None],
  ["PHILLIP", "ANNA", 6, 15, None],
  ["GRACEZ", "JACK", 15, 10, None],
  ["TUSHAR", "JUSTIN", 15, 10, None],
  ["ANTHONY", "PAUL", 14, 16, None],
  ["ANTHONY", "GAB", 15, 13, None],
  ["ANTHONY", "JACK", 15, 7, None],
  # Friday November 3
  ["JUSTIN", "ANTHONY", 6, 15, None],
  ["PAUL", "PHILLIP", 15, 11, None],
  ["PHILLIP", "PAUL", 12, 15, None],
  ["PAUL", "ANNA", 10, 15, None],
  ["TUSHAR", "ANTHONY", 15, 8, None],
  ["ANTHONY", "GAB", 13, 15, None],
  ["GAB", "ANTHONY", 13, 15, None],
  ["PHILLIP", "PAUL", 14, 16, None],
  ["PHILLIP", "ANNA", 10, 15, None],
  ["PHILLIP", "ANNA", 10, 15, None],
  ["PREM", "ANTHONY", 15, 3, None],
  ["PREM", "GAB", 15, 5, None],
  ["PREM", "TUSHAR", 15, 11, None],
  ["PAUL", "PREM", 12, 15, None],
  ["PHILLIP", "GAB", 15, 12, None],
  ["GAB", "PHILLIP", 11, 15, None],
  ["ANTHONY", "TUSHAR", 10, 15, None],
  ["PHILLIP", "GRACEZ", 10, 15, None],
  ["GRACEZ", "PHILLIP", 7, 15, None],
  ["PHILLIP", "PREM", 15, 9, None],
  ["GAB", "JUSTIN", 11, 15, None],
  # Monday November 6
  ["PHILLIP", "PAUL", 15, 11, None],
  ["PAUL", "PHILLIP", 15, 8, None],
#   ["GAB", "JACK", , , None],
  ["JUSTIN", "ANTHONY", 15, 13, None],
  ["PREM", "ANTHONY", 15, 7, None],
  ["ANTHONY", "TUSHAR", 6, 15, None],
  ["JUSTIN", "TUSHAR", 7, 15, None],
  ["TUSHAR", "PREM", 11, 15, None],
  ["PREM", "TUSHAR", 15, 13, None],
  ["PHILLIP", "TUSHAR", 16, 18, None],
  ["PREM", "GAB", 15, 5, None],
  ["GAB", "PREM", 9, 15, None],
  ["JUSTIN", "ANTHONY", 18, 16, None],
  ["PHILLIP", "PAUL", 12, 15, None],
  ["PAUL", "PHILLIP", 15, 9, None],
  ["TUSHAR", "ANTHONY", 15, 13, None],
  ["GAB", "ANTHONY", 12, 15, None],
  ["ANTHONY", "GAB", 15, 13, None],
  ["ANNA", "PHILLIP", 2, 15, None],
  ["PHILLIP", "ANNA", 12, 15, None],
  ["ANNA", "PHILLIP", 15, 10, None],
  # Tuesday November 7
  ["GAB", "GRACEZ", 7, 15, None],
  ["ANTHONY", "GAB", 15, 6, None],
  ["JUSTIN", "ANTHONY", 7, 15, None],
  ["PREM", "JUSTIN", 15, 3, None],
  ["GRACEY", "TUSHAR", 15, 15, None],
  ["ANNA", "PREM", 16, 14, None],
  ["JUSTIN", "GAB", 15, 12, None],
  ["TUSHAR", "GAB", 15, 4, None],
  ["PAUL", "JUSTIN", 12, 15, None],
  ["GRACEY", "GRACEZ", 13, 15, None],
  ["JACK", "GAB", 12, 15, None],
  ["GAB", "JACK", 15, 6, None],
  ["PREM", "PHILLIP", 15, 3, None],
  ["GRACEZ", "PHILLIP", 6, 15, None],
  ["GAB", "ANTHONY", 15, 12, None],
  ["ANTHONY", "GAB", 13, 12, None],
  # Wednesday November 8
  ["JUSTIN", "ANTHONY", 14, 16, None],
  ["TUSHAR", "ANNA", 15, 3, None],
  ["JUSTIN", "PHILLIP", 15, 9, None],
  ["GAB", "GRACEZ", 11, 15, None],
  ["GRACEZ", "PREM", 4, 15, None],
  ["GRACEZ", "JACK", 15, 7, None],
  ["JACK", "GAB", 13, 15, None],
  ["ANTHONY", "PAUL", 15, 11, None],
  ["ANTHONY", "ANNA", 11, 15, None],
  ["PAUL", "PHILLIP", 15, 12, None],
  ["PAUL", "ANNA", 15, 11, None],
  ["PREM", "PAUL", 15, 9, None],
  ["ANTHONY", "JUSTIN", 15, 9, None],
  ["JUSTIN", "JACK", 15, 8, None],
  # Thursday November 9
  ["JUSTIN", "PREM", 12, 15, None],
  ["PAUL", "PHILLIP", 9, 15, None],
  ["PHILLIP", "PAUL", 11, 15, None],
  ["JUSTIN", "ANTHONY", 15, 17, None],
  ["PREM", "ANTHONY", 15, 4, None],
  ["PREM", "GRACEY", 15, 5, None],
  ["GRACEZ", "CARMEN", 9, 15, None],
  ["GAB", "JACK", 10, 15, None],
  ["PHILLIP", "PAUL", 11, 15, None],
  ["GAB", "PAUL", 8, 15, None],
  ["ANTHONY", "PAUL", 13, 15, None],
  ["GRACEZ", "ANTHONY", 10, 15, None],
  ["ANTHONY", "PHILLIP", 13, 15, None],
  ["PREM", "PHILLIP", 15, 7, None],
  ["TUSHAR", "PREM", 15, 13, None],
  ["GAB", "GRACEY", 15, 13, None],
  ["GRACEZ", "GAB", 7, 15, None],
  ["ANTHONY", "GAB", 15, 3, None],
  # Friday November 10
  ["JUSTIN", "ANTHONY", 15, 13, None],
  ["PHILLIP", "TUSHAR", 7, 15, None],
  ["JACK", "GAB", 10, 15, None],
  ["GAB", "PAUL", 9, 15, None],
  ["TUSHAR", "PAUL", 15, 7, None],
  ["JACK", "PHILLIP", 7, 15, None],
  ["PREM", "PHILLIP", 16, 14, None],
  ["PREM", "ANNA", 15, 6, None],
  ["TUSHAR", "PREM", 14, 16, None],
  ["PREM", "ANTHONY", 15, 4, None],
  ["ANTHONY", "TUSHAR", 15, 17, None],
  ["PAUL", "PHILLIP", 11, 15, None],
  ["ANTHONY", "PHILLIP", 7, 15, None],
#   ["ANTHONY", "GAB", 7, 15, None],
  # Monday November 13
  ["ANTHONY", "TUSHAR", 14, 16, None],
  ["JUSTIN", "TUSHAR", 14, 16, None],
  ["PHILLIP", "PAUL", 11, 15, None],
  ["PAUL", "PHILLIP", 13, 15, None],
  ["GRACEZ", "JACK", 10, 15, None],
  ["PREM", "ANTHONY", 15, 10, None],
  ["PHILLIP", "GRACEY", 18, 16, None],
  ["GRACEY", "PHILLIP", 7, 15, None],
  ["GRACEZ", "GAB", 15, 13, None],
  ["JUSTIN", "ANTHONY", 15, 13, None],
  ["ANTHONY", "PREM", 3, 15, None],
  ["PHILLIP", "PAUL", 16, 14, None],
  ["PHILLIP", "ANNA", 15, 12, None],
  ["GAB", "JACK", 5, 15, None],
  ["JUSTIN", "TUSHAR", 13, 15, None],
  ["TUSHAR", "ANTHONY", 15, 11, None],
  # Tuesday November 14
  ["JUSTIN", "ANTHONY", 13, 15, None],
  ["TUSHAR", "PREM", 15, 7, None],
  ["PAUL", "PHILLIP", 12, 15, None],
  ["JACK", "GRACEZ", 15, 8, None],
  ["GRACEZ", "JACK", 15, 13, None],
#   ["TUSHAR", "GRACEY", 15, 13, None],
#   ["JUSTIN", "TUSHAR", 12, 15, None],
#   ["ANNA", "GRACEY", 15, 13, None],
#   ["TUSHAR", "GRACEY", 15, 13, None],
  ["PAUL", "PHILLIP", 15, 11, None],
  ["PAUL", "GRACEZ", 15, 5, None],
  ["GRACEZ", "JACK", 15, 11, None],
  ["GAB", "ANTHONY", 9, 15, None],
  ["ANNA", "PAUL", 10, 15, None],
  ["JUSTIN", "GRACEZ", 10, 15, None],
  ["JACK", "GAB", 11, 15, None],
  ["GAB", "GRACEZ", 13, 15, None],
  # Wednesday November 15
  ["GRACEZ", "GRACEY", 6, 15, None],
  ["GRACEZ", "GAB", 9, 15, None],
  ["JUSTIN", "ANTHONY", 15, 11, None],
  ["JUSTIN", "PAUL", 15, 12, None],
  ["ANTHONY", "GAB", 12, 15, None],
  ["GAB", "ANTHONY", 15, 12, None],
  ["ANNA", "JUSTIN", 15, 6, None],
  ["JUSTIN", "ANTHONY", 15, 17, None],
  ["PAUL", "ANTHONY", 15, 11, None],
  ["JACK", "GRACEZ", 9, 15, None],
  # Thursday November 16
  ["JUSTIN", "ANTHONY", 11, 15, None],
  ["JUSTIN", "GRACEY", 15, 12, None],
  ["PREM", "ANTHONY", 15, 3, None],
  ["GAB", "GRACEZ", 13, 15, None],
  ["JUSTIN", "ANTHONY", 10, 15, None],
  ["PREM", "ANTHONY", 15, 5, None],
  ["PAUL", "JACK", 15, 11, None],
  ["PAUL", "PHILLIP", 11, 15, None],
  ["PREM", "GRACEZ", 15, 3, None],
  ["PAUL", "PREM", 7, 15, None],
  ["GRACEZ", "TUSHAR", 11, 15, None],
  ["GAB", "ANTHONY", 14, 16, None],
  ["ANTHONY", "PREM", 5, 15, None],
  ["ANTHONY", "PREM", 6, 15, None],
  # Friday November 17
  ["ANTHONY", "GAB", 15, 11, None],
  ["PREM", "ANTHONY", 15, 7, None],
  ["ANTHONY", "JUSTIN", 17, 15, None],
  ["JUSTIN", "ANTHONY", 13, 15, None],
#   ["TUSHAR", "ANTHONY", 15, 15, None],
  ["ANTHONY", "TUSHAR", 13, 15, None],
  ["PAUL", "JUSTIN", 15, 12, None],
  ["PAUL", "PREM", 13, 15, None],
#   ["PREM", "TUSHAR", 15, 15, None],
  ["GRACEZ", "GAB", 10, 15, None],
  ["GRACEZ", "JACK", 15, 8, None],
  ["GAB", "JACK", 14, 16, None],
  ["PHILLIP", "ANNA", 15, 10, None],
  ["ANNA", "PHILLIP", 15, 8, None],
  ["PHILLIP", "ANNA", 15, 13, None],
  # Monday November 20
  ["GRACEZ", "JACK", 13, 15, None],
  ["JUSTIN", "ANTHONY", 11, 15, None],
  ["PAUL", "ANTHONY", 18, 16, None],
  ["ANTHONY", "TUSHAR", 8, 15, None],
  ["GRACEZ", "GRACEY", 15, 7, None],
  ["GRACEZ", "TUSHAR", 8, 15, None],
  # Tuesday November 21
  ["PAUL", "JUSTIN", 15, 7, None],
  ["ANTHONY", "TUSHAR", 11, 15, None],
  ["JUSTIN", "GRACEY", 15, 10, None],
  ["JUSTIN", "GAB", 15, 7, None],
  ["JACK", "GAB", 15, 13, None],
  ["JUSTIN", "TUSHAR", 9, 15, None],
  ["GAB", "TUSHAR", 9, 15, None],
  ["PREM", "GRACEY", 15, 7, None],
  ["JACK", "PAUL", 15, 13, None],
  ["GRACEZ", "PAUL", 13, 15, None],
  ["GRACEZ", "GAB", 15, 10, None],
  ["PREM", "PAUL", 15, 6, None],
  ["PREM", "ANNA", 12, 15, None],
  ["ANTHONY", "GRACEZ", 15, 5, None],
  ["ANTHONY", "PREM", 10, 15, None],
  ["GAB", "GRACEZ", 12, 15, None],
  ["GRACEZ", "GAB", 15, 13, None],
  # Wednesday November 22
  ["GRACEZ", "PREM", 5, 15, None],
  ["ANTHONY", "GAB", 15, 7, None],
  ["PREM", "JUSTIN", 15, 7, None],
  ["GAB", "ANTHONY", 5, 15, None],
  ["JACK", "GAB", 12, 15, None],
  ["GAB", "JACK", 13, 15, None],
  ["GRACEZ", "PAUL", 13, 15, None],
  ["ANTHONY", "GAB", 15, 8, None],
  ["ANTHONY", "PAUL", 13, 15, None],
  ["ANTHONY", "JACK", 15, 7, None],
  ["PREM", "ANTHONY", 15, 11, None],
  ["PREM", "ANNA", 10, 15, None],
  # Thursday November 23
  ["PAUL", "JACK", 15, 9, None],
  ["PAUL", "GAB", 15, 3, None],
  ["PREM", "TUSHAR", 15, 11, None],
  ["GRACEZ", "GAB", 8, 15, None],
  ["TUSHAR", "GAB", 15, 13, None],
  ["ANTHONY", "JUSTIN", 15, 13, None],
  ["ANTHONY", "GAB", 15, 11, None],
  ["ANTHONY", "PAUL", 11, 15, None],
  ["GRACEY", "TUSHAR", 15, 13, None],
  ["GAB", "PREM", 2, 15, None],
  ["GAB", "PREM", 4, 15, None],
  ["PAUL", "PREM", 11, 15, None],
  ["ANNA", "PREM", 10, 15, None],
  ["GRACEZ", "JACK", 12, 15, None],
#   ["GAB", "JACK", 12, 15, None],
  ["ANTHONY", "TUSHAR", 18, 20, None],
  ["PREM", "JUSTIN", 15, 7, None],
  ["PREM", "ANTHONY", 15, 3, None],
  ["ANTHONY", "TUSHAR", 12, 15, None],
  ["PAUL", "TUSHAR", 11, 15, None],
  ["PREM", "ANTHONY", 15, 3, None],
  # Monday November 27
  ["GAB", "PAUL", 12, 15, None],
  ["GRACEZ", "PAUL", 17, 19, None],
  ["ANTHONY", "TUSHAR", 16, 18, None],
  ["ANTHONY", "PREM", 7, 15, None],
  ["GAB", "ANTHONY", 13, 15, None],
  ["TUSHAR", "ANTHONY", 15, 12, None],
  ["GAB", "GRACEZ", 17, 15, None],
  # Tuesday November 28
  ["PAUL", "JACK", 15, 12, None],
  ["JUSTIN", "ANTHONY", 13, 15, None],
  ["PREM", "GRACEY", 15, 0, None],
  ["ANNA", "GRACEY", 15, 13, None],
  ["GAB", "PAUL", 12, 15, None],
  ["JUSTIN", "PAUL", 15, 11, None],
  ["GRACEZ", "JACK", 10, 15, None],
  ["GRACEZ", "PREM", 3, 15, None],
  ["ANTHONY", "GAB", 15, 12, None],
  ["GAB", "ANTHONY", 9, 15, None],
  ["TUSHAR", "ANTHONY", 15, 12, None],
  ["PREM", "ANTHONY", 15, 8, None],
  ["JUSTIN", "ANTHONY", 15, 13, None],
  # Wednesday November 29
  ["TUSHAR", "ANTHONY", 15, 12, None],
  ["PHILLIP", "PAUL", 15, 17, None],
  ["JUSTIN", "ANTHONY", 15, 13, None],
  ["GRACEY", "CERI", 15, 5, None],
  ["JUSTIN", "PREM", 7, 15, None],
  ["GRACEY", "PREM", 3, 15, None],
  ["ANNA", "PREM", 15, 11, None],
  ["ANTHONY", "PAUL", 13, 15, None],
  ["PAUL", "GRACEZ", 15, 6, None],
  ["JUSTIN", "ANTHONY", 15, 11, None],
  ["GAB", "GRACEZ", 15, 12, None],
  ["PAUL", "JACK", 15, 6, None],
  ["GRACEY", "JUSTIN", 13, 15, None],
  ["GAB", "JACK", 12, 15, None],
  ["GAB", "JUSTIN", 12, 15, None],
  ["TUSHAR", "ANNA", 15, 8, None],
  # Thursday November 30
  ["GAB", "JUSTIN", 15, 17, None],
  ["PAUL", "JUSTIN", 14, 16, None],
  ["PREM", "TUSHAR", 15, 7, None],
  ["GAB", "PAUL", 12, 15, None],
  ["PREM", "PAUL", 15, 17, None],
  ["PAUL", "ANNA", 15, 13, None],
  ["JUSTIN", "JACK", 15, 11, None],
  ["ANTHONY", "GAB", 17, 15, None],
  ["GAB", "ANTHONY", 13, 15, None],
#   ["JUSTIN", "ANTHONY", 13, 15, None],
#   ["TUSHAR", "ANTHONY", 13, 15, None],
#   ["TUSHAR", "GRACEY", 13, 15, None],
  ["PREM", "ANTHONY", 15, 9, None],
  ["TUSHAR", "ANTHONY", 13, 15, None],
  ["PAUL", "ANTHONY", 15, 13, None],
  ["PAUL", "ANNA", 13, 15, None],
  # Friday December 1
  ["ANTHONY", "JUSTIN", 15, 1, None],
  ["PHILLIP", "GRACEZ", 15, 18, None],
  ["GRACEZ", "PHILLIP", 15, 12, None],
  ["GAB", "PHILLIP", 15, 11, None],
  ["GAB", "GRACEY", 13, 15, None],
  ["GAB", "JACK", 16, 14, None],
  ["GAB", "ANTHONY", 18, 16, None],
  ["WILSON", "PREM", 3, 15, None],
  ["PREM", "WILSON", 15, 1, None],
  ["PHILLIP", "ANNA", 20, 18, None],
  ["ANNA", "PHILLIP", 13, 15, None],
  ["PHILLIP", "ANNA", 14, 16, None],
  ["GRACEZ", "TUSHAR", 13, 15, None],
#   # Monday December 4
  ["ANTHONY", "JUSTIN", 15, 13, None],
  ["PHILLIP", "JEREMY", 15, 13, None],
  ["GAB", "ANTHONY", 11, 15, None],
  ["PHILLIP", "JEREMY", 9, 15, None],
  ["PAUL", "JEREMY", 15, 10, None],
  ["ANNA", "JEREMY", 13, 15, None],
  ["PREM", "JEREMY", 13, 15, None],
  ["ANTHONY", "TUSHAR", 13, 15, None],
  ["JUSTIN", "ANTHONY", 15, 13, None],
  ["PREM", "TUSHAR", 14, 16, None],
  ["GRACEZ", "JUSTIN", 13, 15, None],
  ["PHILLIP", "PAUL", 11, 15, None],
  ["PHILLIP", "GAB", 15, 6, None],
  ["PHILLIP", "PREM", 10, 15, None],
  ["JEREMY", "ANNA", 15, 10, None],
  ["ANTHONY", "TUSHAR", 11, 15, None],
  ["ANTHONY", "JUSTIN", 11, 15, None],
  ["ANTHONY", "GAB", 15, 8, None],
  ["GAB", "ANTHONY", 15, 7, None],
  ["GRACEZ", "JACK", 15, 7, None],
  ["PHILLIP", "ANNA", 15, 13, None],
  ["PHILLIP", "JEREMY", 11, 15, None],
#   # Tuesday December 5
  ["JUSTIN", "ANTHONY", 6, 15, None],
  ["PHILLIP", "JEREMY", 15, 13, None],
  ["PAUL", "GAB", 15, 10, None],
  ["ANTHONY", "GAB", 15, 10, None],
  ["ANNA", "JEREMY", 15, 13, None],
  ["GRACEY", "TUSHAR", 9, 15, None],
  ["GRACEY", "PREM", 3, 15, None],
  ["PREM", "JEREMY", 15, 12, None],
  ["PAUL", "ANNA", 16, 14, None],
  ["JEREMY", "GAB", 15, 6, None],
  ["JEREMY", "GAB", 15, 9, None],
  ["JUSTIN", "TUSHAR", 7, 15, None],
  ["PAUL", "JEREMY", 7, 15, None],
  ["PHILLIP", "JEREMY", 13, 15, None],
  ["TUSHAR", "JEREMY", 15, 12, None],
  ["PAUL", "JUSTIN", 15, 10, None],
  ["GRACEZ", "JACK", 11, 15, None],
  ["GRACEZ", "PAUL", 5, 15, None],
  ["GRACEZ", "TUSHAR", 10, 15, None],
  ["GRACEY", "GRACEZ", 14, 16, None],
  ["JEREMY", "ANNA", 15, 12, None],
  ["ANNA", "JEREMY", 15, 12, None],
  ["ANTHONY", "JUSTIN", 15, 7, None],
#   # Wednesday December 6
  ["GRACEZ", "PHILLIP", 15, 7, None],
  ["PHILLIP", "GRACEZ", 15, 4, None],
  ["GRACEY", "GAB", 13, 15, None],
  ["GRACEZ", "GAB", 7, 15, None],
  ["PHILLIP", "PREM", 6, 15, None],
  ["WILSON", "GAB", 7, 15, None],
  ["JEREMY", "ANNA", 12, 15, None],
  ["JEREMY", "ANNA", 11, 15, None],
  ["TUSHAR", "ANTHONY", 10, 15, None],
  ["ANTHONY", "PREM", 6, 15, None],
  ["PREM", "TUSHAR", 15, 9, None],
  ["ANTHONY", "GAB", 13, 15, None],
  ["GAB", "JUSTIN", 9, 15, None],
  ["PAUL", "JUSTIN", 15, 9, None],
  ["PAUL", "GAB", 15, 9, None],
  ["ANTHONY", "PAUL", 16, 14, None],
  ["PHILLIP", "ANNA", 10, 15, None],
  ["JUSTIN", "ANTHONY", 10, 15, None],
  ["JUSTIN", "GRACEZ", 15, 11, None],
  ["JUSTIN", "PREM", 14, 16, None],
  ["JUSTIN", "TUSHAR", 15, 11, None],
  ["ANTHONY", "ANNA", 9, 15, None],
  ["GRACEY", "PHILLIP", 15, 13, None],
  ["GRACEZ", "GAB", 15, 12, None],
  ["TUSHAR", "ANNA", 15, 7, None],
#   # Thursday December 7
  ["JEREMY", "PHILLIP", 15, 4, None],
  ["JEREMY", "ANNA", 15, 7, None],
  ["ANNA", "JEREMY", 9, 15, None],
  ["PAUL", "JACK", 16, 14, None],
  ["PREM", "JUSTIN", 15, 9, None],
  ["GAB", "GRACEZ", 15, 9, None],
  ["TUSHAR", "PHILLIP", 15, 11, None],
  ["PHILLIP", "GRACEY", 15, 9, None],
  ["GRACEZ", "GAB", 10, 15, None],
  ["JEREMY", "PAUL", 15, 12, None],
  ["PAUL", "ANNA", 15, 11, None],
  ["ANTHONY", "GAB", 15, 7, None],
  ["ANTHONY", "GRACEY", 15, 13, None],
  ["GRACEZ", "GRACEY", 15, 4, None],
  ["JEREMY", "PREM", 15, 13, None],
#   # Friday December 8
  ["GRACEY", "GAB", 15, 9, None],
  ["PREM", "JUSTIN", 15, 13, None],
  ["ANNA", "JEREMY", 9, 15, None],
  ["TUSHAR", "JUSTIN", 15, 0, None],
  ["PAUL", "PREM", 15, 13, None],
  ["JEREMY", "PAUL", 15, 9, None],
  ["GRACEZ", "JUSTIN", 15, 13, None],
  ["ANTHONY", "PHILLIP", 10, 15, None],
  ["GAB", "JACK", 15, 9, None],
  ["JACK", "GRACEZ", 15, 13, None],
  ["PHILLIP", "PAUL", 12, 15, None],
  ["TUSHAR", "ANTHONY", 15, 1, None],
  ["ANNA", "GRACEY", 17, 15, None],
  ["JEREMY", "ANNA", 15, 11, None],
  ["GRACEY", "PREM", 6, 15, None],
  ["ANNA", "JEREMY", 15, 13, None],
  ["JEREMY", "PHILLIP", 9, 15, None],
  ["PHILLIP", "JEREMY", 20, 18, None],
  ["ANNA", "JEREMY", 7, 15, None],
  ["WILSON", "GAB", 8, 15, None],
  ["WILSON", "GAB", 10, 15, None],
  ["PREM", "JEREMY", 11, 15, None],
#   # Monday December 11
  ["JACK", "GAB", 14, 16, None],
  ["JEREMY", "TUSHAR", 4, 15, None],
  ["JEREMY", "PHILLIP", 13, 15, None],
  ["JUSTIN", "ANTHONY", 15, 17, None],
  ["GRACEZ", "GRACEY", 7, 15, None],
  ["GAB", "WILSON", 15, 5, None],
  ["PHILLIP", "JEREMY", 14, 16, None],
  ["GRACEZ", "GAB", 7, 15, None],
  ["JEREMY", "PHILLIP", 11, 15, None],
  ["ANTHONY", "GAB", 12, 15, None],
  ["PAUL", "ANNA", 16, 14, None],
  ["WILSON", "GRACEZ", 13, 15, None],
  ["WILSON", "GAB", 13, 15, None],
  ["PHILLIP", "PAUL", 15, 11, None],
  ["GRACEZ", "JACK", 11, 15, None],
  ["GRACEZ", "JUSTIN", 15, 11, None],
  ["TUSHAR", "BOGDAN", 15, 6, None],
  ["BOGDAN", "TUSHAR", 4, 15, None],
  ["GAB", "GRACEY", 9, 15, None],
#   # Tuesday December 12
  ["PHILLIP", "ANNA", 16, 14, None],
  ["PHILLIP", "JEREMY", 6, 15, None],
  ["GRACEZ", "GAB", 15, 17, None],
  ["ANTHONY", "PREM", 5, 15, None],
  ["JEREMY", "PHILLIP", 11, 15, None],
  ["PHILLIP", "JEREMY", 10, 15, None],
  ["GAB", "JACK", 15, 4, None],
  ["JUSTIN", "ANTHONY", 12, 15, None],
  ["ANTHONY", "TUSHAR", 7, 15, None],
  ["JEREMY", "ANNA", 15, 4, None],
  ["ANNA", "JEREMY", 10, 15, None],
  ["GAB", "WILSON", 15, 4, None],
  ["GAB", "ANTHONY", 15, 13, None],
  ["GAB", "ANNA", 5, 15, None],
  ["JACK", "PAUL", 9, 15, None],
  ["PAUL", "JUSTIN", 18, 16, None],
  ["PHILLIP", "PAUL", 15, 13, None],
  ["ANTHONY", "GAB", 15, 13, None],
  ["JEREMY", "PHILLIP", 15, 11, None],
  ["PHILLIP", "JEREMY", 19, 21, None],
  ["ANNA", "JEREMY", 6, 15, None],
  ["JEREMY", "PAUL", 12, 15, None],
#   # Wednesday December 13
  ["JEREMY", "TUSHAR", 13, 15, None],
  ["JEREMY", "PHILLIP", 9, 15, None],
  ["PHILLIP", "JEREMY", 8, 15, None],
  ["JEREMY", "PHILLIP", 15, 10, None],
  ["PREM", "TUSHAR", 6, 15, None],
  ["GRACEZ", "JACK", 15, 11, None],
  ["PAUL", "PHILLIP", 15, 6, None],
  ["JEREMY", "PAUL", 15, 6, None],
  ["JUSTIN", "TUSHAR", 14, 16, None],
  ["JEREMY", "PHILLIP", 13, 15, None],
  ["PHILLIP", "JEREMY", 13, 15, None],
  ["JEREMY", "PHILLIP", 15, 12, None],
  ["GRACEZ", "JACK", 17, 15, None],
  ["GRACEZ", "PHILLIP", 7, 15, None],
  ["GRACEZ", "JEREMY", 12, 15, None],
  ["JUSTIN", "ANTHONY", 9, 15, None],
  ["GAB", "GRACEZ", 15, 5, None],
  ["JACK", "GAB", 6, 15, None],
  ["GAB", "TUSHAR", 12, 15, None],
  ["WILSON", "GAB", 4, 15, None],
  ["GAB", "ANTHONY", 13, 15, None],
  ["ANTHONY", "GAB", 16, 18, None],
  ["TUSHAR", "ANTHONY", 15, 12, None],
  # Thursday December 13
  ["JEREMY", "PHILLIP", 15, 10, None],
  ["GRACEZ", "WILSON", 15, 6, None],
  ["JEREMY", "PHILLIP", 15, 10, None],
  ["JEREMY", "ANNA", 12, 15, None],
  ["GAB", "WILSON", 15, 7, None],
  ["GRACEZ", "GAB", 10, 15, None],
  ["GAB", "ANTHONY", 15, 12, None],
  ["GAB", "JACK", 15, 7, None],
  ["JEREMY", "PAUL", 6, 15, None],
  ["PAUL", "JEREMY", 15, 10, None],
  ["PAUL", "TUSHAR", 10, 15, None],
  ["GRACEZ", "JACK", 15, 12, None],
  ["GRACEY", "PHILLIP", 16, 14, None],
  ["PHILLIP", "GRACEY", 16, 14, None],
  ["PHILLIP", "ANNA", 15, 10, None],
  ["JACK", "PAUL", 14, 16, None],
  ["PREM", "JEREMY", 15, 12, None],
  ["JEREMY", "PREM", 9, 15, None],
  ["JEREMY", "ANNA", 15, 9, None],
  ["ANNA", "JEREMY", 15, 13, None],
  ["PHILLIP", "TUSHAR", 15, 11, None],
  ["BOGDAN", "TUSHAR", 7, 11, None],
  ["ANTHONY", "TUSHAR", 10, 15, None],
  ["PREM", "ANTHONY", 15, 5, None],
  ["JEREMY", "TUSHAR", 15, 11, None],
  # Friday December 14
  ["JEREMY", "ANTHONY", 15, 12, None],
  ["GAB", "GRACEY", 9, 15, None],
  ["TUSHAR", "JUSTIN", 15, 12, None],
  ["WILSON", "GAB", 13, 15, None],
  ["WILSON", "GAB", 10, 15, None],
  ["ANTHONY", "WILSON", 15, 4, None],
  ["JACK", "GRACEZ", 16, 14, None],
  ["GAB", "ANTHONY", 13, 15, None],
  ["GAB", "ANTHONY", 20, 22, None],
  ["TUSHAR", "JACK", 15, 11, None],
  ["GRACEZ", "GAB", 14, 16, None],
  ["GAB", "GRACEY", 15, 7, None],
  ["GAB", "JACK", 8, 15, None],
  ["GRACEY", "GRACEZ", 12, 15, None],
  ["GRACEZ", "GRACEY", 15, 8, None],
  ["GAB", "ANTHONY", 14, 16, None],
  ["ANTHONY", "GAB", 13, 15, None],
  ["GAB", "WILSON", 15, 8, None],
  ["WILSON", "GAB", 14, 16, None],
  # Monday December 18
  ["PAUL", "PHILLIP", 15, 11, None],
  ["PREM", "PHILLIP", 10, 15, None],
  ["ANNA", "PHILLIP", 10, 15, None],
  ["JUSTIN", "TUSHAR", 14, 16, None],
  ["JUSTIN", "ANTHONY", 14, 16, None],
  ["PAUL", "ANTHONY", 15, 13, None],
  ["GRACEY", "TUSHAR", 5, 15, None],
  ["GRACEY", "PREM", 9, 15, None],
  ["ANNA", "GRACEY", 15, 11, None],
  ["ANNA", "PHILLIP", 15, 11, None],
  ["PHILLIP", "ANNA", 15, 13, None],
  ["ANNA", "PHILLIP", 15, 9, None],
  ["GRACEY", "GAB", 15, 11, None],
  ["PAUL", "JACK", 15, 11, None],
  ["GRACEZ", "JACK", 15, 11, None],
  ["PREM", "TUSHAR", 15, 11, None],
  ["PREM", "GRACEY", 20, 18, None],
  ["TUSHAR", "GRACEY", 15, 8, None],
  ["GRACEZ", "GRACEY", 8, 15, None],
  ["GAB", "ANTHONY", 15, 8, None],
  ["ANTHONY", "GAB", 4, 15, None],
  ["PREM", "GAB", 14, 16, None],
  # Wednesday December 20
  ["JUSTIN", "TUSHAR", 15, 17, None],
  ["WILSON", "GAB", 15, 8, None],
  ["GRACEZ", "GRACEY", 10, 15, None],
  ["GRACEY", "TUSHAR", 10, 15, None],
  ["GAB", "GRACEY", 15, 13, None],
  ["JUSTIN", "TUSHAR", 15, 13, None],
  ["PHILLIP", "ANTHONY", 16, 14, None],
  # Friday December 22
  ["PAUL", "ANTHONY", 15, 17, None],
  ["ANTHONY", "PAUL", 11, 15, None],
  # Thursday December 28
  ["PAUL", "PHILLIP", 15, 12, None],
  ["PHILLIP", "PAUL", 16, 14, None],
  ["PAUL", "PHILLIP", 15, 10, None],
  ["PAUL", "JACK", 15, 11, None],
  ["TUSHAR", "GRACEY", 15, 12, None],
  # Friday December 29
  ["GAB", "JACK", 15, 12, None],
  ["PREM", "GAB", 15, 8, None],
  ["GAB", "PAUL", 4, 15, None],
  ["ANTHONY", "PAUL", 14, 16, None],
  ["PAUL", "PREM", 15, 8, None],
]